Refactor Docker configuration and update related dependencies
The Docker configuration has been refactored to accommodate changes in the application's behavior. The docker-compose file has been updated, and as a result, unnecessary files were deleted including the entrypoint.sh, hive-site.xml, and docker-compose.yaml. Changes were also made to the Dockerfile to adjust the build process. Dependencies in requirements.txt were updated, and modifications were made to the project's settings in .yml files. Round off this process through README.md update for the new instructions.

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,30 +1,57 @@
-ARG OPENJDK_VERSION=8
-FROM eclipse-temurin:${OPENJDK_VERSION}-jre
+FROM openjdk:16-slim
 
-ARG BUILD_DATE
-ARG SPARK_VERSION=3.3.0
-ARG HADOOP_VERSION=3
+# Lifted from: https://github.com/joshuarobinson/presto-on-k8s/blob/1c91f0b97c3b7b58bdcdec5ad6697b42e50d74c7/hive_metastore/Dockerfile
 
-LABEL org.label-schema.name="Apache Spark ${SPARK_VERSION}" \
-      org.label-schema.build-date=$BUILD_DATE \
-      org.label-schema.version=$SPARK_VERSION
+# see https://hadoop.apache.org/releases.html
+ARG HADOOP_VERSION=3.3.0
+# see https://downloads.apache.org/hive/
+ARG HIVE_METASTORE_VERSION=3.0.0
+# see https://jdbc.postgresql.org/download.html#current
+ARG POSTGRES_CONNECTOR_VERSION=42.2.18
 
-ENV SPARK_HOME /usr/spark
-ENV PATH="/usr/spark/bin:/usr/spark/sbin:${PATH}"
+# Set necessary environment variables.
+ENV HADOOP_HOME="/opt/hadoop"
+ENV PATH="/opt/spark/bin:/opt/hadoop/bin:${PATH}"
+ENV DATABASE_DRIVER=org.postgresql.Driver
+ENV DATABASE_TYPE=postgres
+ENV DATABASE_TYPE_JDBC=postgresql
+ENV DATABASE_PORT=5432
 
-RUN apt-get update && \
-    apt-get install -y wget netcat procps libpostgresql-jdbc-java && \
-    wget -q "http://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" && \
-    tar xzf "spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" && \
-    rm "spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" && \
-    mv "spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}" /usr/spark && \
-    ln -s /usr/share/java/postgresql-jdbc4.jar /usr/spark/jars/postgresql-jdbc4.jar && \
-    apt-get remove -y wget && \
-    apt-get autoremove -y && \
-    apt-get clean
+WORKDIR /app
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
-COPY entrypoint.sh /scripts/
-RUN chmod +x /scripts/entrypoint.sh
+# hadolint ignore=DL3008
+RUN \
+  echo "Install OS dependencies" && \
+    build_deps="curl" && \
+    apt-get update -y && \
+    apt-get install -y $build_deps net-tools --no-install-recommends && \
+  echo "Download and extract the Hadoop binary package" && \
+    curl https://archive.apache.org/dist/hadoop/core/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz \
+    | tar xvz -C /opt/ && \
+    ln -s /opt/hadoop-$HADOOP_VERSION /opt/hadoop && \
+    rm -r /opt/hadoop/share/doc && \
+  echo "Add S3a jars to the classpath using this hack" && \
+    ln -s /opt/hadoop/share/hadoop/tools/lib/hadoop-aws* /opt/hadoop/share/hadoop/common/lib/ && \
+    ln -s /opt/hadoop/share/hadoop/tools/lib/aws-java-sdk* /opt/hadoop/share/hadoop/common/lib/ && \
+  echo "Download and install the standalone metastore binary" && \
+    curl https://downloads.apache.org/hive/hive-standalone-metastore-$HIVE_METASTORE_VERSION/hive-standalone-metastore-$HIVE_METASTORE_VERSION-bin.tar.gz \
+    | tar xvz -C /opt/ && \
+    ln -s /opt/apache-hive-metastore-$HIVE_METASTORE_VERSION-bin /opt/hive-metastore && \
+  echo "Fix 'java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument'" && \
+  echo "Keep this until this lands: https://issues.apache.org/jira/browse/HIVE-22915" && \
+    rm /opt/apache-hive-metastore-$HIVE_METASTORE_VERSION-bin/lib/guava-19.0.jar && \
+    cp /opt/hadoop-$HADOOP_VERSION/share/hadoop/hdfs/lib/guava-27.0-jre.jar /opt/apache-hive-metastore-$HIVE_METASTORE_VERSION-bin/lib/ && \
+  echo "Download and install the database connector" && \
+    curl -L https://jdbc.postgresql.org/download/postgresql-$POSTGRES_CONNECTOR_VERSION.jar --output /opt/postgresql-$POSTGRES_CONNECTOR_VERSION.jar && \
+    ln -s /opt/postgresql-$POSTGRES_CONNECTOR_VERSION.jar /opt/hadoop/share/hadoop/common/lib/ && \
+    ln -s /opt/postgresql-$POSTGRES_CONNECTOR_VERSION.jar /opt/hive-metastore/lib/ && \
+  echo "Purge build artifacts" && \
+    apt-get purge -y --auto-remove $build_deps && \
+    apt-get clean && \
+    rm -rf /var/lib/apt/lists/*
 
-ENTRYPOINT ["/scripts/entrypoint.sh"]
-CMD ["--help"]
+COPY run.sh run.sh
+
+CMD [ "./run.sh" ]
+HEALTHCHECK CMD [ "sh", "-c", "netstat -ln | grep 9083" ]
